name: Production Deploy

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_VM4 }}

    - name: Deploy .NET microservice to VM
      run: |
        ssh -o StrictHostKeyChecking=no your_user@your_server_ip << 'EOF'
          cd /path/to/your/dotnet-app
          git pull origin $(git rev-parse --abbrev-ref HEAD)
          dotnet restore
          dotnet publish -c Release -o ./publish
          docker-compose build --no-cache
          docker-compose up -d
        EOF
